#!/bin/bash

for i in {1..39}
do
	dir=train_lists/trainlist4
	if [ $i -lt 31 ]
	then
		dir=train_lists/trainlist3
	fi
	if [ $i -lt 21 ]
	then
		dir=train_lists/trainlist2
	fi
	if [ $i -lt 11 ]
	then 
		dir=train_lists/trainlist1
	fi
	line=`ls -R mfcc_e_d_a/songs_train/ | grep '.mfc' | awk 'NR >= '$i' && NR <= '$i' { print }'`
	output=`echo "mfcc_e_d_a/songs_train/Acoustic_Fake/"$line`
	echo $output >> $dir
done

for i in {40..91}
do
	dir=train_lists/trainlist9
	if [ $i -lt 81 ]
	then
		dir=train_lists/trainlist8
	fi
	if [ $i -lt 71 ]
	then
	        dir=train_lists/trainlist7
	fi
	if [ $i -lt 61 ]
	then
	        dir=train_lists/trainlist6
	fi
	if [ $i -lt 51 ]
	then
	        dir=train_lists/trainlist5
	fi
	line=`ls -R mfcc_e_d_a/songs_train/ | grep '.mfc' | awk 'NR >= '$i' && NR <= '$i' { print }'`
	output=`echo "mfcc_e_d_a/songs_train/Electric_Fake/"$line`
	echo $output >> $dir
done

for i in {1..4}
do
	listfile="train_lists/trainlist"$i
	tabsfile="tabs_lists/tabslist"$i
	finalfile="tabs_lists/finallist"$i
	filelines=`cat $listfile`
	for line in $filelines;
	do	
		lastline=${line/.mfc/.lab}
		cat $lastline | tr -d "\r" | sort -u >> $tabsfile
	done

	cat $tabsfile | sort -u > $finalfile
done
for i in {5..9}
do
	listfile="train_lists/trainlist"$i
	tabsfile="tabs_lists/tabslist"$i
	finalfile="tabs_lists/finallist"$i
	filelines=`cat $listfile`
	for line in $filelines;
	do
		lastline=${line/.mfc/.lab}
		cat $lastline | tr -d "\r" | sort -u >> $tabsfile
	done
	
	cat $tabsfile | sort -u > $finalfile
done

hmmproto="hmm0/Hmm_proto"

for i in {1..9}
do
	finalfile="tabs_lists/finallist"$i
	hmmdefs="hmm0/hmmdefs"$i
	tabslist=`cat $finalfile`
	hmmproto="hmm0/Hmm_proto"
	cat $hmmproto | awk "NR >= 1 && NR <= 3 { print }" > $hmmdefs
	for line in $tabslist;
	do
		newline=`echo $line | tr -d "\n\r"`
		echo ~h \"$newline\" >> $hmmdefs
		cat $hmmproto | awk "NR >= 5 && NR <= 17 { print }" >> $hmmdefs	
	done
done

