#!/bin/bash

# --- Crea un nou fitxer .mlf amb els tabs filtrats ---

filelines=`cat songs.mlf`
newfile='songs2.mlf'
string='Tab'
for line in $filelines
do
	if [[ $line == *$string* ]]
	then
		if grep -Fxq $line counts/filtered_tabs.txt
                then
	                echo $line >> $newfile
		else
			echo "GarbageTab" >> $newfile
		fi		
	else
		echo $line >> $newfile
	fi
done
