#!/bin/bash

# --- Crea fitxers labs amb els tabs filtrats i substitueix els que no existeixen per GarbageTab ---

fileslist=`ls -R mfcc_e_d_a/songs_train/ | grep ".lab"`
index=0
for file in $fileslist;
do
	if [ $index -lt 39 ]
	then
		d="Acoustic_Fake/"
	else
		d="Electric_Fake/"
	fi
	dir=`dirname $file`
	labfile="mfcc_e_d_a/songs_train/"$d$file
	finalfile="garbage_labs/"$d$file
	filelines=`cat $labfile`
	
	for line in $filelines;
	do
		if grep -Fxq $line counts/filtered_tabs.txt
		then
			echo $line >> $finalfile
		else
			echo "GarbageTab" >> $finalfile
		fi
	done
	index=$((index+1))
done
sed -i "1s/.*/GarbageTab/" counts/filtered_tabs.txt
